# Generated by Django 3.0.4 on 2020-04-08 10:12

import common.storage
from django.db import migrations, models
import fonds.models


class Migration(migrations.Migration):

    dependencies = [
        ('fonds', '0002_auto_20200307_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondprofile',
            name='logo',
            field=models.ImageField(default='logo_default.jpg', storage=common.storage.OverwriteStorage(), upload_to=fonds.models.upload_location),
        ),
        migrations.DeleteModel(
            name='FondLogo',
        ),
    ]
