# Generated by Django 3.0.4 on 2020-04-09 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fonds', '0003_auto_20200408_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='fond',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.RenameField(
            model_name='fondapplication',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='fondthread',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='fondthreadpost',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='investmentfond',
            name='day_time',
        ),
        migrations.AddField(
            model_name='investmentfond',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FondNotification',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
