# Generated by Django 3.0.4 on 2020-03-07 10:40

from django.db import migrations


def create_global_chat_room(apps, schema_editor):
    """
    Create the global chat room
    """

    ChatRoom = apps.get_model("users", "ChatRoom")

    if not ChatRoom.objects.filter(name="Global").exists():
        ChatRoom.objects.create(name="Global")


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_global_chat_room)
    ]
