# Generated by Django 3.0.4 on 2020-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_create_global_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
