# Generated by Django 3.0.4 on 2020-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='This user prefers to keep an air of mystery about them.'),
        ),
    ]
