# Generated by Django 3.0.4 on 2020-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200402_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default='logo_default.jpg', upload_to='company_logo/'),
        ),
    ]
