# Generated by Django 3.0.4 on 2020-04-08 10:12

import common.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default='logo_default.jpg', storage=common.storage.OverwriteStorage(), upload_to=users.models.upload_location),
        ),
    ]
