# Generated by Django 3.0.4 on 2020-04-09 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200408_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='threadpost',
            old_name='date_time',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_time',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
