# Generated by Django 3.0.4 on 2020-03-07 10:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('runtime', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('day_time_issued', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'bond',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('isin', models.CharField(max_length=10, unique=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('shares', models.PositiveIntegerField(default=1000000)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='DepotPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price_bought', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('day_time', models.DateTimeField(auto_now_add=True)),
                ('private_depot', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'depot_position',
            },
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('day_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interest_rate',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default=None, max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('amount', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PrivateDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
            ],
            options={
                'db_table': 'private_depot',
            },
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Order', 'Order'), ('Bond', 'Bond')], max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=40)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('received', models.BooleanField()),
                ('day_time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'db_table': 'statement_of_account',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('price_bought', models.DecimalField(decimal_places=2, default=1, max_digits=40)),
                ('day_time', models.DateTimeField(auto_now_add=True)),
                ('buyer_pd', models.BooleanField(default=False)),
                ('seller_pd', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_buyer', to='core.Company')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_of', to='core.Company')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_seller', to='core.Company')),
            ],
            options={
                'db_table': 'trade',
            },
        ),
        migrations.CreateModel(
            name='DynamicOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Order')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('dynamic_value', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
            ],
            options={
                'db_table': 'dynamic_order',
            },
            bases=('core.order',),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Trade')),
            ],
            options={
                'db_table': 'trade_history',
            },
        ),
        migrations.CreateModel(
            name='StatementTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.StatementOfAccount')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Trade')),
            ],
            options={
                'db_table': 'statement_trade',
            },
        ),
    ]
