# Generated by Django 3.0.4 on 2020-03-07 10:39

from django.db import migrations


def create_interest_rate(apps, schema_editor):
    InterestRate = apps.get_model("core", "InterestRate")
    if not InterestRate.objects.exists():
        InterestRate.objects.create(rate=2.5)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200307_1035'),
    ]
    operations = [migrations.RunPython(create_interest_rate)]
