# Generated by Django 3.0.4 on 2020-03-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200323_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementofaccount',
            old_name='trade_id',
            new_name='trade',
        ),
    ]
