# Generated by Django 3.0.4 on 2020-04-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200323_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='day_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='depotposition',
            old_name='day_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='interestrate',
            old_name='day_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='statementofaccount',
            old_name='day_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='day_time',
            new_name='created',
        ),
    ]
