# Generated by Django 3.0.4 on 2020-04-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200409_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created',
            new_name='updated',
        ),
    ]
