# Generated by Django 3.0.4 on 2020-03-07 10:39

from django.db import migrations

from tsg.const import CENTRALBANK, START_CASH


def create_centralbank(apps, schema_editor):
    """
    Creates the centralbank. The centralbank needs to exist on startup.

    When a user singes up and creates a new company, the centralbank will hold
    100% of the shares.
    """

    Company = apps.get_model('core', 'Company')
    if not Company.objects.filter(name=CENTRALBANK).exists():
        company = Company.objects.create(name=CENTRALBANK, user=None, cash=START_CASH)

        # signals are not triggered on data migration
        from core.signals import create_models_new_company
        create_models_new_company(None, company, True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200409_1500'),
        ('stats', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_centralbank)
    ]
