# Generated by Django 3.0.4 on 2020-04-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_create_centralbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='depot_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DepotPosition'),
        ),
    ]
