# Generated by Django 3.0.4 on 2020-04-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_depot_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='depot_position',
        ),
    ]
