# Generated by Django 3.0.4 on 2020-03-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFigures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=40)),
                ('ttoc', models.DecimalField(decimal_places=2, max_digits=40)),
                ('cdgr', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('share_price', models.DecimalField(decimal_places=2, default=1, max_digits=40)),
                ('activity', models.IntegerField(default=0)),
                ('free_float', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'db_table': 'key_figures',
            },
        ),
        migrations.CreateModel(
            name='HistoryCompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_shares', models.PositiveIntegerField()),
                ('joined', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'db_table': 'company_history',
            },
        ),
        migrations.CreateModel(
            name='PastKeyFigures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=40)),
                ('ttoc', models.DecimalField(decimal_places=2, max_digits=40)),
                ('cdgr', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('share_price', models.DecimalField(decimal_places=2, default=1, max_digits=40)),
                ('activity', models.IntegerField(default=0)),
                ('free_float', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('shares', models.PositiveIntegerField()),
                ('day', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'db_table': 'past_key_figures',
                'unique_together': {('company', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CompanyVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_volume', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('sell_volume', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('day', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'db_table': 'company_volume',
                'unique_together': {('company', 'day')},
            },
        ),
    ]
