name: Websockets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/chat
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make deps
    
    
    - name: Lint
      run: make lint

    - name: Test
      run: |
        make cov
        bash <(curl https://codecov.io/bash) -f coverage.txt -F chat
  
    - name: Build
      run: make build
